### ISSUE TITLE
clinicadl train   --visualization       Save results in visualization folder

### ISSUE THREAD

**Issue by 921974496** [aramis-lab/clinicadl#10]
Where can I view this result? And how to draw ROC curve and calculate AUC?

**Comment by 921974496** [comment]
Hello，
How to set up dropout during training？

**Comment by mdiazmel** [comment]
Hi,

> Where can I view this result? And how to draw ROC curve and calculate AUC?

The visualization folder stores images for one subject in NIfTI format after multiples epochs. Visualizers for NIfTI format can be easily grabbed on the web.  To draw the ROC and calculate AUC we suggest you to activate the [TensorBoardX](https://github.com/lanpa/tensorboardX) module while running the training and follow in a web interface the evolution of the curves.

**Comment by alexandreroutier** [comment]
> Hello，
> How to set up dropout during training？

Hello @921974496,

@14thibea created PR #11 to address your question (currently, this is not possible). Once reviewed, this will be available for AD-DL.

Best,
Alex

**Comment by mdiazmel** [comment]
Hi, 
PR #11 was merged to master. Now, it's possible to to set `dropout` parameter during the training for the concerned layers.

**Comment by 921974496** [comment]
> Hi,
> PR #11 was merged to master. Now, it's possible to to set `dropout` parameter during the training for the concerned layers.

Thanks

**Comment by 921974496** [comment]
When I run clinicidl classify I encounter some problems：
File "/home/geng/AD-DL/clinicadl/clinicadl/tools/deep_learning/iotools.py", line 164, in commandline_to_json
    if commandline_arg_dic['split'] is None:
KeyError: 'split'

Is my network_dir parameter wrong?  My network_dir parameter is the best_model_dir folder in train output_dir

**Comment by 921974496** [comment]
The command I used is       clinicadl classify patch / home / geng / ADNI2 / test / caps / home / geng / ADNI2 / test / tsv / home / geng / ADNI2 / test / output / home / geng / ADNI2 / resault / best_model_dir

**Comment by 921974496** [comment]
> Hi,
> PR #11 was merged to master. Now, it's possible to to set `dropout` parameter during the training for the concerned layers.

The “class Parameters” should also be modified in the “clinicadl / clinicadl / tools / deep_learning / iotools.py file”

**Comment by mdiazmel** [comment]
> When I run clinicidl classify I encounter some problems：

Hi, 
the `classify` task is currently WIP (The brand new issue #15 clarifies this). 
However, you can try to use one of the scripts available to evaluate your trained model (see  `clinicadl/clinicadl/subject_level/evaluation.py` for example).
