### ISSUE TITLE
Missing info.json after 'pip install clinicadl'

### ISSUE THREAD

**Issue by alexandreroutier** [aramis-lab/clinicadl#114]
From [Google Forum](https://groups.google.com/g/clinica-user/c/D7vC8VknOVU), I just noticed that there is no `MANIFEST.in` explaining why the `info.json` error 😳  

Hopefully, this should be enough for running `t1-extensive` using normal installation.

Alex

**Comment by mdiazmel** [comment]
Closed by PR #115. 
Changes will be applied to the new version of the package.
