### ISSUE TITLE
Commandline source code refactoring

### ISSUE THREAD

**Issue by 14thibea** [aramis-lab/clinicadl#161]
The file `cli.py` is very heavy and difficult to adapt for new comers.
We would like to have one file per functionality for the command line (similar than in Clinica) to enhance readability.

**Comment by mdiazmel** [comment]
There is a suggestion of @ghisvail for using [Click](https://click.palletsprojects.com/en/8.0.x/) in Clinica. Maybe, we can profit from this experience to refactor the command line in ClinicaDL and implement this improvement here.

**Comment by ghisvail** [comment]
You can get a good idea of how it would look like [here](https://github.com/aramis-lab/clinica/pull/275)
