### ISSUE TITLE
I don't understand this line about ROI Patch Selection

### ISSUE THREAD

**Issue by BanDoong** [aramis-lab/clinicadl#169]
In your ROI Training Document said that 

`If no ROI is specified, the inputs will correspond to two patches of size 50x50x50 voxels manually centered on each hippocampus.`

But the source code about the Extract ROI Patches looks like choose one of left or right hippocampus (Not both, But only one of left or right).

https://github.com/aramis-lab/clinicadl/blob/164d0884c0afb78c5c6700b80bc358c89e1f5559/clinicadl/clinicadl/tools/deep_learning/data.py#L680

Do I think wrong?

If I think wrong, Please notice me what the input of Multi CNN?
In case of, t1-linear & no Masks about roi (no ROI list)
Is it right that the left or right hippocampus?

Best Regards,

**Comment by 14thibea** [comment]
Hello!

Both hippocampi are used, but they are seen sequentially (not concatenated together).

- If you use a single-CNN, the classifier will be trained on both hippocampi
- If you use a multi-CNN, 2 CNNs are trained (one on the left hippocampus only, the second one the right hippocampus only).

If you want to give both hippocampi at the same time, you can define one single mask enclosing both hippocampi. Then you have two options:

1. running deeplearning-prepare-data with ROI option
2. running deeplearning-prepare-data with image option and perform ROI extraction on-the-fly.

Best regards,

**Comment by 14thibea** [comment]
Hello,

Can I close the issue or are some explanations still needed?

Best,

**Comment by 14thibea** [comment]
As this discussion is not active anymore, I close the issue.
Please reopen it if other explanations are needed!
