### ISSUE TITLE
About eMethod

### ISSUE THREAD

**Issue by snorlaxse** [aramis-lab/clinicadl#17]
《Convolutional neural networks for classification of Alzheimer's disease: Overview and reproducible evaluation》eMethod 1. 2, 3, and 4 mentioned have no  corresponding link. Pelease provide the URL，thanks a lot.

**Comment by 14thibea** [comment]
Hello,

Supplementary Material are available on [MedIA](https://www.sciencedirect.com/science/article/abs/pii/S1361841520300591) on the same page than the article.
They are also on [arXiv](https://arxiv.org/abs/1904.07773) or [Hal](https://hal.archives-ouvertes.fr/hal-02562504) at the end of the PDF which can be downloaded.
