### ISSUE TITLE
clinicadl didn't use GPU well

### ISSUE THREAD

**Issue by BanDoong** [aramis-lab/clinicadl#173]
I found that Clinica don't use GPU well.

My Clinicadl version is 0.2.2

And I uses  
OS : Linux
CUDA : 11.1
CUDNN : 8
GPU : A100-SXM4-40GB

nvidia-smi is 
<img width="422" alt="image" src="https://user-images.githubusercontent.com/56647416/126661344-7cc61fb3-9eef-4f9f-bbbf-7456f8d517bc.png">

**GPU utils. is 0% most of time.**

top is
<img width="472" alt="image" src="https://user-images.githubusercontent.com/56647416/126661379-f0ce3ac2-e8fc-4f9b-b450-1bfb6a1bb5cd.png">

Do I something wrong thing?
If you have any solutions about it, I will be helpful to me.

Best Regards,

**Comment by BanDoong** [comment]
I don't know where I'm using a lot of CPU resources.

**Comment by 14thibea** [comment]
Hello,

Sorry for the delay,
Could you please send the command and the JSON file generated (commandline.json).

**Comment by BanDoong** [comment]
Sorry, I have some problem regarding Kubernetes.

The issue is from the Kubernetes.

Thank you for your caring.
