### ISSUE TITLE
Improve `extract` pipeline

### ISSUE THREAD

**Issue by ravih18** [aramis-lab/clinicadl#186]
Improve CLI by dividing the command line with different modes to split the options.
Pass the `extracted_features` option from train to extract to save it in the preprocessing json to avoid confusion when loading data on the fly.
Re use Nipype to allow parallel processing.

**Comment by mdiazmel** [comment]
This issue is partially covered by PR #201.

**Comment by ravih18** [comment]
Issue #238 closes this.
