### ISSUE TITLE
train can't find output of extract

### ISSUE THREAD

**Issue by usadiqgriffin** [aramis-lab/clinicadl#19]
Hi,

I am running clinicaDL to preprocess, extract and then train a DL model, in sequence. Here are the commands I ran:

clinicadl preprocessing /ad_dl/data/ /ad_dl/data/caps_dir ../pAD.tsv work_dir

clinicadl extract /ad_dl/data/caps_dir  ../pAD.tsv work_dir slice

These two seem to execute without error. At the end of extract, I can see some .pt file created inside /ad_dl/data/caps_dir/subjects/sub-A00027159/ses-DS2/deeplearning_prepare_data/slice_based/t1_linear/.

But when I run the train command, I get the following error:

command: clinicadl train slice /ad_dl/data/caps_dir/ /ad_dl/ /ad_dl/data/ Conv4_FC3
Error:

FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anac3/envs/clinicadl_adprog/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anac3/envs/clinicadl_adprog/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
.....
FileNotFoundError: [Errno 2] No such file or directory: '/ad_dl/data/caps_dir/subjects/sub-A00027544/ses-DS2/t1/preprocessing_dl/sub-A00027544_ses-DS2_space-MNI_res-1x1x1.pt'

Seems like train is looking for files in the wrong location (I only see a directory called t1_linear inside ses-DS2) or perhaps preprocessing didnt finish?

**Comment by mdiazmel** [comment]
Hi @usadiqgriffin ,

Thanks for your interest in `clinicadl`. 

The problem seem to be that you're using a version of the code between two commits when we were changing the structure of the folders containing the tensors. We wish to use an structure for the tensors coherent with the [BIDS/CAPS specifications](http://www.clinica.run/doc/CAPS/Introduction/). 

Try to update your local repository (`git pull`), current commit (136e649) can handle the training stage with the new folder structure containing the tensors.

Sorry for the inconvenience. This software is currently under development (_beta testing_) and this kind of issues could show up frequently.

Cheers,
