### ISSUE TITLE
.sh files to .py and preprocessing

### ISSUE THREAD

**Issue by pv116** [aramis-lab/clinicadl#2]
Hi,
First of all thank you very much for sharing this- I am working on a very similar final year university project and this is extremely useful to me. I was wondering a couple of things:
1) I see most of your code files are .sh, would you happen to have .py versions too?
2) For the data preprocessing, would you happen to have the scripts for the 'minimal' and 'extensive' procedures (along with the 4 main stages of: (i) bias field correction (ii) intensity rescaling and standardisation (iii) skull stripping (iv) image registration) as outlined in your report please?
Many thanks in advance for your support!

**Comment by mdiazmel** [comment]
Hi @pv116 ,
Thanks for your interest in this project. 

> 1. I see most of your code files are .sh, would you happen to have .py versions too?

Files in the folder `clinicadl/scripts` are mostly `bash scripts` (.sh files) that can be useful to run the package in computing clusters. You can use them to create your own scripts or you can also use clinicadl as a package in your own python files.

> For the data preprocessing, would you happen to have the scripts for the 'minimal' and 'extensive' procedures (along with the 4 main stages of: (i) bias field correction (ii) intensity rescaling and standardisation (iii) skull stripping (iv) image registration) as outlined in your report please?

This is work in progress in this moment. We are currently refactoring the preprocessing part and a new release will simplify the use of the *minimal* and *extensive* procedures.

**Comment by pv116** [comment]
Thank you very much for the responses; this makes it clearer now. Looking forward to your future work!
