### ISSUE TITLE
No module named 'clinicadl.generate'

### ISSUE THREAD

**Issue by jerryajay** [aramis-lab/clinicadl#208]
I followed every step from https://clinicadl.readthedocs.io/en/stable/Installation/ . When `clinicadl -h` is typed, I get the error: 
```
Traceback (most recent call last):
  File "/home/jajay/anaconda3/envs/clinicadlEnv/bin/clinicadl", line 5, in <module>
    from clinicadl.cmdline import cli
  File "/home/jajay/anaconda3/envs/clinicadlEnv/lib/python3.7/site-packages/clinicadl/cmdline.py", line 6, in <module>
    from clinicadl.generate.generate_cli import cli as generate_cli
ModuleNotFoundError: No module named 'clinicadl.generate'

```

**Comment by 14thibea** [comment]
Hello!

Thank you for reporting the bug, could you tell us which version of ClinicaDL is running?

**Comment by jerryajay** [comment]
While re-installing `pip install clinicadl`, it showed:
```
pip install clinicadl
Collecting clinicadl
  Using cached clinicadl-1.0.0-py2.py3-none-any.whl (119 kB)

```

**Comment by 14thibea** [comment]
I created a PR to fix the problem.
Meanwhile you can use ClinicaDL by cloning the repo, and installing it in editable mode by running `pip install -e .` in the repo.

**Comment by jerryajay** [comment]
Cloning the repo and installing it in editable mode fixed the issue. Thanks.

**Comment by mdiazmel** [comment]
Hi!

We propose a new release (v1.0.1) that fix the problem! It can be installed again by using `pip install clinicadl`.

Thanks for reporting this @jerryajay !

**Comment by jerryajay** [comment]
You're welcome @mdiazmel .
