### ISSUE TITLE
Seems A bug? cannot import name 'T1LinearCLI' from 'clinica.pipelines.t1_linear.t1_linear_cli

### ISSUE THREAD

**Issue by fpeng2003** [aramis-lab/clinicadl#235]
I run my code and tutorial example, run into same error: cannot import name 'T1LinearCLI' from 'clinica.pipelines.t1_linear.t1_linear_cli

!clinicadl preprocessing quality-check t1-linear OasisCaps QC_result.tsv
!clinicadl classify ./OasisCaps ./OasisCaps/participants.tsv ./model_exp3_splits_1 'test-Oasis'

Traceback (most recent call last):
  File "/usr/local/bin/clinicadl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/clinicadl/main.py", line 9, in main
    parser = cli.parse_command_line()
  File "/usr/local/lib/python3.7/dist-packages/clinicadl/cli.py", line 378, in parse_command_line
    from clinica.pipelines.t1_linear.t1_linear_cli import T1LinearCLI
ImportError: cannot import name 'T1LinearCLI' from 'clinica.pipelines.t1_linear.t1_linear_cli' (/usr/local/lib/python3.7/dist-packages/clinica/pipelines/t1_linear/t1_linear_cli.py)

Please help!

**Comment by 14thibea** [comment]
Hello !

Current version of ClinicaDL does not support anymore `t1-linear` preprocessing, as it is now done by Clinica.
To use it please use the command `clinica run t1-linear` and it should work!

**Comment by fpeng2003** [comment]
Thank you very much for your quick response, it means a lot to me. I struggled a whole day on this issue. I followed the tutorial:
https://aramislab.paris.inria.fr/clinicadl/tuto/Notebooks-AD-DL/preprocessing.html#tensor-extraction-with-the-deeplearning-prepare-data-pipeline.
I did run the folllowing command without problem.
!clinica run t1-linear ./OasisBids_example ./OasisCaps_example --n_procs 2

The problem commands are: 
!clinicadl preprocessing quality-check t1-linear OasisCaps QC_result.tsv
!clinicadl classify ./OasisCaps ./OasisCaps/participants.tsv ./model_exp3_splits_1 'test-Oasis'
it seems that everytime run clinicadl, same error appear. I even try to install clinicadl 1.0.3, even worse. 

Would you please let me know the how to run:? what commands to use?
!clinicadl preprocessing quality-check t1-linear OasisCaps QC_result.tsv
!clinicadl classify ./OasisCaps ./OasisCaps/participants.tsv ./model_exp3_splits_1 'test-Oasis'

Where to find correct tutorial? 

Thanks a lot

**Comment by 14thibea** [comment]
Hello,

The tutorials were not updated with the latest versions (sorry for that, it will be done soon)
You will find the correct commands in the [documentation](https://clinicadl.readthedocs.io/en/stable) which is up-to-date 

The correct commands would be:
`clinicadl quality-check t1-linear CAPS_DIRECTORY OUTPUT_TSV`
`clinicadl predict INPUT_MAPS_DIRECTORY DATA_GROUP`

**Comment by fpeng2003** [comment]
Thank you very much for your response. I really like your tutorial, clear and practical.  Do you know any tool to process OASIS-3 Dataset, or any example program? Thanks

**Comment by 14thibea** [comment]
Hello,

The BIDS converter of OASIS-3 was recently added to Clinica (https://aramislab.paris.inria.fr/clinica/docs/public/latest/Converters/OASIS3TOBIDS/)
It works on the same way than the OASIS-1 converter, once converted you can use the other tools of Clinica / ClinicaDL on it!
If you have any issue using this converter please open an issue on Clinica repo https://github.com/aramis-lab/clinica

**Comment by SonaLily** [comment]
Hello, I am fpeng2003, but with another account. 
I did test and got errors. I post my questions here: https://github.com/aramis-lab/clinica/issues/458
Issue: error !clinica convert oasis3-to-bids Oasis3test Oasis3test/ClinicalData Oasis3BidsRun #458

==================
I got error when I do:
!clinica convert oasis3-to-bids Oasis3test Oasis3test/ClinicalData Oasis3BidsRun

File "/usr/local/lib/python3.7/dist-packages/clinica/iotools/converters/oasis3_to_bids/oasis3_utils.py", line 47, in find_clinical_data
raise FileNotFoundError("Clinical data not found or incomplete")
FileNotFoundError: Clinical data not found or incomplete

I do have this file in Oasis3test/ClinicalData: ADRCclinicalData.csv which I downloaded from xnat.
My question is: Is any special requirement on this file? is it possible you can provide an file with correct format?

I also tried to dowdload Bids directly from xnat and tried to process those data by:

!clinica run t1-linear Oasis3BIDStest Oasis3Cap --n_procs 2
I got following message:
2021-10-10 12:13:47,002:WARNING:Could not determine if /content/gdrive/MyDrive/AIOasis3Azheimer/Oasis3Cap is a CAPS or BIDS directory. Clinica will assume this is a CAPS directory.
2021-10-10 12:13:50,102:ERROR:Clinica faced error(s) while trying to read files in your BIDS directory.
Clinica encountered 4 problem(s) while getting T1w MRI:
* (sub-OAS30001 | ses-d0129): More than 1 file found:
/content/gdrive/MyDrive/AIOasis3Azheimer/Oasis3BIDStest/sub-OAS30001/ses-d0129/anat/sub-OAS30001_ses-d0129_run-01_T1w.nii.gz
/content/gdrive/MyDrive/AIOasis3Azheimer/Oasis3BIDStest/sub-OAS30001/ses-d0129/anat/sub-OAS30001_ses-d0129_run-02_T1w.nii.gz
* (sub-OAS30001 | ses-d0757): More than 1 file found

My question is: is it possible to process bids files downloaded directly from Oasis3 by clinica? if yes, how to do?

Thanks  a lot!

**Comment by ghisvail** [comment]
@SonaLily please avoid double posting to facilitate support. Thanks.

**Comment by 14thibea** [comment]
I am closing this issue as it was answered on Clinica repo https://github.com/aramis-lab/clinica/issues/458.
