### ISSUE TITLE
Option `prepare_dl=True` by default?

### ISSUE THREAD

**Issue by mdiazmel** [aramis-lab/clinicadl#24]
The option `prepare_dl` allow to perform patch extraction and slice extraction during the training.
Suggested in PR #20.

**Comment by mdiazmel** [comment]
Hi @14thibea,

Current situation is as follows:

If `prepare_dl=True` the dataloader uses the files previously extracted and stored in the drive. Otherwise, it performs `patch` or `slice` extraction during the training on-the-fly.

Both approaches have pros and cons, e.g., storing the patches and/or slices in the drive saves gpu memory (this can help if the gpu card not enough performant) but training process can be slower. On the other hand, extracting these features on-the-fly could accelerate the training but you need a good gpu card.

What do you think that should be the behavior by default? 

(BTW, we should change the name of this option, it could be confusing...)

**Comment by 14thibea** [comment]
Finally the argument was renamed `use_extracted_patches` and `use_extracted_slices` in https://github.com/aramis-lab/AD-DL/pull/20. The default behaviour is extraction on-the-fly.
