### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by theguardsgod** [aramis-lab/clinicadl#247]
![1635235839(1)](https://user-images.githubusercontent.com/44542822/138835675-ef5c3ebe-177d-4f0b-bd66-d9cf3568bf1b.png)
when I want to train the model with the following code. 
clinicadl train classification ./OasisCaps_example extract_1635220292.json ./oasis_label ./oasis_maps

it print TypeError: 'type' object is not subscriptable

**Comment by 14thibea** [comment]
Hello!

Thank you for your interest in ClinicaDL! Could you please give us the version of python and ClinicaDL you are using?
It seems that your environment does not handle [`typing`](https://docs.python.org/3/library/typing.html) correctly...

**Comment by theguardsgod** [comment]
(CDL) [chenyuliu@pbcmlg01 CDL]$ python -V
Python 3.7.5

Name: clinicadl
Version: 1.0.3
Summary: Deep learning classification with clinica
Home-page: https://github.com/aramis-lab/clinicadl
Author: ARAMIS Lab
Author-email: None
License: MIT license
Location: /home/chenyuliu/.local/lib/python3.7/site-packages
Requires: numpy, tensorboard, toml, torch, clinica, pynvml, click
Required-by: 


> Hello!
> 
> Thank you for your interest in ClinicaDL! Could you please give us the version of python and ClinicaDL you are using? It seems that your environment does not handle [`typing`](https://docs.python.org/3/library/typing.html) correctly...

**Comment by 14thibea** [comment]
On my side it is working with python 3.7.5
Could you please give us the Pytorch and cuda version you are using?

**Comment by 14thibea** [comment]
Actually the problem may come from the version of [`typing-extensions`](https://pypi.org/project/typing-extensions), which is a requirement of Pytorch (from version 1.8.0).
Could you retrieve the version installed in your environment?

**Comment by theguardsgod** [comment]
> Actually the problem may come from the version of [`typing-extensions`](https://pypi.org/project/typing-extensions), which is a requirement of Pytorch (from version 1.8.0). Could you retrieve the version installed in your environment?

Thank you, the problem has been solved.
