### ISSUE TITLE
Subparsers of training `patch`

### ISSUE THREAD

**Issue by mdiazmel** [aramis-lab/clinicadl#27]
Could subparsers of `patch` be `autoencoder`, `multi-cnn` and `single-cnn` instead of `autoencoder` and `cnn` ? This would make the used realize that these choices exist and that they are quite different (also some arguments are specific to `multi-cnn`).

Suggested in PR #20.

**Comment by 14thibea** [comment]
Done in https://github.com/aramis-lab/AD-DL/pull/20
