### ISSUE TITLE
Verbose is not taken into account

### ISSUE THREAD

**Issue by 14thibea** [aramis-lab/clinicadl#276]
It seems that verbose is not set to the value asked by the user in the current version.
Maybe it should become an option of all functions of ClinicaDL? Or is there another way to handle it with click?

**Comment by mdiazmel** [comment]
Yes, I noticed that when launching in JZ... It's really annoying! Need to be put higher in the priority list. 
Normally there is a way to handle with click ([I put here the Clinica's example](https://github.com/aramis-lab/clinica/blob/dev/clinica/cmdline.py) to remember at the moment of proposing a fix).

**Comment by ravih18** [comment]
Addressed in #294
