### ISSUE TITLE
Issue to run : clinicadl random-search with Oasis3 data

### ISSUE THREAD

**Issue by SonaLily** [aramis-lab/clinicadl#278]
Hello

When I ran:
!clinicadl random-search /content/gdrive/MyDrive/AlexisAlzheimerAIData/oasis3data/RandomSearchHypterP RSPoutput 

I got following error:
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 13 column 1 char 443)

To simply this issue, I ran
toml_options = toml.load(path.join(launch_directory, "random_search.toml"))
and got same error. It seems the toml.load do not like random_search.toml which I directly copy from documention of your website:
https://clinicadl.readthedocs.io/en/stable/RandomSearch/
[Random_Search]
# Mandatory args
caps_directory = "/content/gdrive/MyDrive/AlexisAlzheimerAIData/oasis3data/Oasis3D4CAPS"
tsv_path = "/content/gdrive/MyDrive/AlexisAlzheimerAIData/oasis3data/Oasis3D2ClinicalData/Oasis3Data"
preprocessing_json = "extract_image.json"
network_task = "classification"
n_convblocks = [2, 6]
first_conv_width = [4, 8, 16, 32]
n_fcblocks = [1, 3]
# Options
channels_limit = 64
d_reduction = ["MaxPooling", "stride"]
network_normalization = ["BatchNorm", "InstanceNorm", None]  (This is line 13, the program raised error here)
wd_bool = [true, false]

[Architecture]
dropout = [0.0, 0.9]

[Data]
diagnoses = ["AD", "CN"]

[Optimization]
epochs = 100
learning_rate = [2, 5]
weight_decay = [2, 4]

My question is: what should be the right value for:
network_normalization = ["BatchNorm", "InstanceNorm", None]  (This is line 13, the program raised error here)

Thanks

**Comment by 14thibea** [comment]
Hello,

Could you tell us where in the documentation you copied `random_search.toml` so I can fix it?

Actually `None` does not exist in TOML file, you may want to replace this line by
`network_normalization = ["BatchNorm", "InstanceNorm", "None"]`
with quotes around `None`.

**Comment by SonaLily** [comment]
After I remove None as you suggested, it works. 
I forgot where I copied it from, maybe from your clinicadl source code. If I see it again, I will let you know. Thank you.

**Comment by 14thibea** [comment]
Ok thank you!
Meanwhile I close this issue.
