### ISSUE TITLE
Rename `preprocessing` options

### ISSUE THREAD

**Issue by mdiazmel** [aramis-lab/clinicadl#28]
Preprocessings that can be chosen in the commandline are `linear` and `mni`. For more homogeneity `mni` could be renamed `extensive` or `t1-volume` (and `linear` would be `t1-linear`).

Suggested in PR #20.

**Comment by 14thibea** [comment]
Done for train in https://github.com/aramis-lab/AD-DL/pull/20.
There are still inconsistencies in generate though.

**Comment by 14thibea** [comment]
This issue will be subdivided in several issues depending on the pipeline affected. Here are the objectives for the parser `train` only:
- The argument must be mandatory for all pipelines.
- The options will be renamed `t1-linear` and `t1-extensive`.
