### ISSUE TITLE
Problem wiht:!clinicadl train slice cnn <caps_directory> "t1-linear" data/labels_lists/train results/slice_cnn resnet18 --n_splits 5

### ISSUE THREAD

**Issue by SonaLily** [aramis-lab/clinicadl#283]
Hello, I tried to do transfer learning as following:
!clinicadl train slice cnn Oasis1Data/Oasis1D4Caps "t1-linear" Oasis1Data/programOutput/slice_cnn resnet18 --n_splits 5
Note: Oasis1Data/programOutput/slice_cnn is the output dir I specified.

(Based on instruction:https://github.com/aramis-lab/Notebooks-AD-DL/blob/master/training.ipynb)
-------
# 2D-slice single-CNN training
!clinicadl train slice cnn -h
#!clinicadl train slice cnn <caps_directory> "t1-linear" data/labels_lists/train results/slice_cnn resnet18 --n_splits 5
-----------
I got following error:
Usage: clinicadl train [OPTIONS] {classification|r
                       egression|reconstruction}
                       CAPS_DIRECTORY
                       PREPROCESSING_JSON
                       TSV_DIRECTORY
                       OUTPUT_MAPS_DIRECTORY
Try 'clinicadl train -h' for help.

Error: Invalid value for '{classification|regression|reconstruction}': 'slice' is not one of 'classification', 'regression', 'reconstruction'.

How to do transfer learning?

Thanks

**Comment by ravih18** [comment]
Hello @SonaLily,

The notebook you used works with an old version of ClinicaDL (`<1.0`) and will not work with recent versions of ClinicaDL.

If you use a version `>=1.0`, which seems to be the case, please refer to the [documentation](https://clinicadl.readthedocs.io/en/stable/) that is up-to-date. 

⚠️ Actually the command line used to train a model is totally different !

In your case, you will need to use the `train` command line with the task that you try to achieve (`classification` I believe) and give the mandatory arguments as specified in the error message: 
- CAPS_DIRECTORY => Oasis1Data/Oasis1D4Caps
- PREPROCESSING_JSON => the name of the file that has been created when extracting tensors
- TSV_DIRECTORY => path to your cross validations TSV (if you have 5 splits)
- OUTPUT_MAPS_DIRECTORY => Oasis1Data/programOutput/slice_cnn

Then complete your command line with the options you would like to use:
- `--architecture resnet18`
- `--n_splits 5`
- and your specific arguments for transfert learning `--transfer_path` and `--transfer_selection_metric`.

The command you will use should look like:
```
clinicadl train classification Oasis1Data/Oasis1D4Caps /name/of/json /path/to/tsv Oasis1Data/programOutput/slice_cnn --architecture resnet18 --n_splits 5 --transfer_path /path/to/transfert 
``` 

You will find more [information about transfert learning in the documentation](https://clinicadl.readthedocs.io/en/latest/Train/Details/#transfer-learning).

I hope all these changes does not lead to confusion. Do not hesitate if it is not clear.

**Comment by SonaLily** [comment]
Hello! Thanks for all the detailed suggestions!
I just have a quick question for the --transfer_path /path/to/transfert command, what do I put into the path part of the command? And how do I get the transfer files?

**Comment by ravih18** [comment]
Hello,

the `--transfer_path` option takes the path to a MAPS directory where the weights of your source model are stored. The fact that it is a MAPS and not directly a pytorch file might actually be limitation.
The source model is a pre-trained model, so the transfer file are a pre-trained model that you will use has a source model.

FYI a new version of ClinicaDL (`v1.1.0`) has been released, with a few [new features and bug fix](https://github.com/aramis-lab/clinicadl/releases/tag/v1.1.0) !
