### ISSUE TITLE
 ClinicaDL Documentation Interpretation with gradient maps

### ISSUE THREAD

**Issue by mselimata** [aramis-lab/clinicadl#291]
Is there an easy tutorial available for showing output of clinicadl interpret pt files?

**Comment by ravih18** [comment]
Hello @mselimata,

Thanks for your interest in ClinicaDL.

`.pt` files are [pytorch serialized files](https://pytorch.org/docs/stable/notes/serialization.html) that can be read using [`torch.load()` function](https://pytorch.org/docs/stable/generated/torch.load.html). You can then use the loaded pytorch tensor to make plots using any visualization library.

We are trying to make some tutorials that should be available in a few weeks with some examples.
