### ISSUE TITLE
What is your clinica version？

### ISSUE THREAD

**Issue by 921974496** [aramis-lab/clinicadl#3]
Hi i am very interested in your job，I encountered some problems, hope you can help me。
ImportError: No module named clinica.utils.inputs

**Comment by 921974496** [comment]
What is your pytorch version？

**Comment by mdiazmel** [comment]
Hi, 
thanks for your interest in clinicadl!

I just updated the main README.md file with the current versions for dependencies (clinica >=0.3.2 and Pytorch >= 1.1.0). 

Did you follow the instructions described there?
In resume: 
```
conda create --name clinicadl_env python=3.6 jupyter
conda activate clinicadl_env
conda install -c aramislab -c conda-forge clinica

git clone git@github.com:aramis-lab/AD-DL.git
cd AD-DL
pip install -r requirements.txt
conda install -c pytorch pytorch torchvision
```
then install `clinicadl` inside your active environment
```
cd clinicadl
pip install -e .
```
I hope that this can works. Otherwise, send me the output message of the error.

**Comment by 921974496** [comment]
File "/home/AD-DL/clinicadl/clinicadl/preprocessing/T1_linear.py", line 25, in preprocessing_t1w
    from clinica.utils.inputs import check_bids_folder
ImportError: No module named clinica.utils.inputs

**Comment by 921974496** [comment]
# packages in environment at /home/geng/anaconda3/envs/clinicadl_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
apipkg                    1.5                        py_0    conda-forge
argcomplete               1.9.4                 py36_1000    conda-forge
attrs                     19.3.0                     py_0    defaults
backcall                  0.1.0                    py36_0    defaults
blas                      1.1                    openblas    conda-forge
bleach                    3.1.0                    py36_0    defaults
blosc                     1.17.1               he1b5a44_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py36_0    conda-forge
cffi                      1.14.0           py36hd463f26_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
citeproc-py               0.4.0                    pypi_0    pypi
click                     7.0                        py_0    conda-forge
clinica                   0.3.2                    py36_0    <unknown>
cloudpickle               1.3.0                      py_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
cryptography              2.8              py36h72c5cf5_1    conda-forge
cudatoolkit               10.1.243             h6bb024c_0    <unknown>
cvxopt                    1.2.3           py36_blas_openblash4e5d371_200  [blas_openblas]  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py36h516909a_0    conda-forge
dask-core                 2.11.0                     py_0    conda-forge
dbus                      1.13.12              h746ee38_0    defaults
decorator                 4.4.1                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
dipy                      1.1.0            py36hc1659b7_0    conda-forge
dsdp                      5.8             blas_openblash5c7cb9b_1202  [blas_openblas]  conda-forge
duecredit                 0.6.4                    py36_0    <unknown>
entrypoints               0.3                      py36_0    defaults
execnet                   1.7.1                      py_0    conda-forge
expat                     2.2.6                he6710b0_0    defaults
fastcache                 1.1.0            py36h516909a_0    conda-forge
fftw                      3.3.8           nompi_h7f3a6c3_1110    conda-forge
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.9.1                h8a8886c_1    defaults
funcsigs                  1.0.2                      py_3    conda-forge
future                    0.18.2                   py36_0    conda-forge
glib                      2.63.1               h5a9c865_0    defaults
glpk                      4.65              he80fd80_1002    conda-forge
gmp                       6.1.2                h6c8ec71_1    defaults
gmpy2                     2.1.0b1          py36h04dde30_0    conda-forge
grabbit                   0.1.1            py34h340ac2b_0    aramislab
gsl                       2.4             blas_openblash5c7cb9b_1004  [blas_openblas]  conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
h5py                      2.10.0          nompi_py36h513d04c_102    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.9                        py_1    conda-forge
imageio                   2.8.0                      py_0    conda-forge
importlib_metadata        1.5.0                    py36_0    defaults
intel-openmp              2020.0                      166    defaults
ipykernel                 5.1.4            py36h39e3cac_0    defaults
ipython                   7.12.0           py36h5ca1d4c_0    defaults
ipython_genutils          0.2.0                    py36_0    defaults
ipywidgets                7.5.1                      py_0    defaults
isodate                   0.6.0                      py_1    conda-forge
jedi                      0.16.0                   py36_0    defaults
jinja2                    2.11.1                     py_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
jsonschema                3.2.0                    py36_0    defaults
jupyter                   1.0.0                    py36_7    defaults
jupyter_client            5.3.4                    py36_0    defaults
jupyter_console           6.1.0                      py_0    defaults
jupyter_core              4.6.1                    py36_0    defaults
keepalive                 0.5                        py_1    conda-forge
kiwisolver                1.1.0            py36hc9558a2_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libpng                    1.6.37               hbc83047_0    defaults
libsodium                 1.0.16               h1bed415_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_0    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.13                 h1bed415_1    defaults
libxgboost                0.80              hf484d3e_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxml2                   2.9.9                hea5a465_1    defaults
libxslt                   1.1.32            hae48121_1003    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
lxml                      3.8.0                    py36_0    conda-forge
lz4                       3.0.2            py36hd79334b_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py36h7b6447c_0    defaults
matplotlib                3.1.1            py36h5429711_0    defaults
metis                     5.1.0             he1b5a44_1005    conda-forge
mistune                   0.8.4            py36h7b6447c_0    defaults
mkl                       2020.0                      166    <unknown>
mock                      3.0.5                    py36_0    conda-forge
more-itertools            8.2.0                      py_0    conda-forge
mpc                       1.1.0             h04dde30_1006    conda-forge
mpfr                      4.0.2                he80fd80_0    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
nbconvert                 5.6.1                    py36_0    defaults
nbformat                  5.0.4                      py_0    defaults
ncurses                   6.2                  he6710b0_0    defaults
networkx                  1.11                     py36_0    conda-forge
nibabel                   3.0.1                      py_0    conda-forge
nilearn                   0.5.0                    pypi_0    pypi
ninja                     1.10.0               hc9558a2_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nipy                      0.4.1           py36h3010b51_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nipype                    1.1.2                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nose                      1.3.7                 py36_1003    conda-forge
notebook                  6.0.3                    py36_0    defaults
num2words                 0.5.6                    pypi_0    pypi
numexpr                   2.7.1            py36hb3f55d8_0    conda-forge
numpy                     1.15.4          py36_blas_openblash1522bff_1000  [blas_openblas]  conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.1            py36hb3f55d8_0    conda-forge
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py36_1    defaults
parso                     0.6.1                      py_0    defaults
pcre                      8.43                 he6710b0_0    defaults
pexpect                   4.8.0                    py36_0    defaults
pickleshare               0.7.5                    py36_0    defaults
pillow                    7.0.0            py36hb39fc2d_0    defaults
pip                       9.0.3                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
plinkio                   0.9.6            py34h6de997a_0    <unknown>
pluggy                    0.12.0                     py_0    conda-forge
prometheus_client         0.7.1                      py_0    defaults
prompt_toolkit            3.0.3                      py_0    defaults
protobuf                  3.11.3                   pypi_0    pypi
prov                      1.5.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
psutil                    5.7.0            py36h516909a_0    conda-forge
ptyprocess                0.6.0                    py36_0    defaults
py                        1.8.1                      py_0    conda-forge
py-xgboost                0.80            py36hf484d3e_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pybids                    0.5.1                    pypi_0    pypi
pycparser                 2.20                       py_0    conda-forge
pydicom                   1.4.2                      py_0    conda-forge
pydot                     1.2.4                      py_0    conda-forge
pydotplus                 2.0.2                      py_1    conda-forge
pygments                  2.5.2                      py_0    defaults
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyqt                      5.9.2            py36h05f1152_2    defaults
pyrsistent                0.15.7           py36h7b6447c_0    defaults
pysocks                   1.7.1                    py36_0    conda-forge
pytables                  3.6.1            py36h9f153d1_1    conda-forge
pytest                    5.3.5                    py36_1    conda-forge
pytest-forked             1.1.2                      py_0    conda-forge
pytest-xdist              1.31.0                     py_0    conda-forge
python                    3.6.10               h0371630_0    defaults
python-dateutil           2.8.1                      py_0    defaults
pytorch                   1.4.0           py3.6_cuda10.1.243_cudnn7.6.3_0    <unknown>
pytz                      2019.3                     py_0    conda-forge
pywavelets                1.1.1            py36hc1659b7_0    conda-forge
pyzmq                     18.1.1           py36he6710b0_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
qtconsole                 4.6.0                      py_1    defaults
rdflib                    4.2.2                 py36_1000    conda-forge
readline                  7.0                  h7b6447c_5    defaults
requests                  2.23.0                   py36_0    conda-forge
scikit-image              0.14.1          py36hf484d3e_1004    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
scikit-learn              0.20.0          py36_blas_openblashebff5e3_1201  [blas_openblas]  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
scipy                     1.2.1           py36_blas_openblash1522bff_0  [blas_openblas]  conda-forge
send2trash                1.5.0                    py36_0    defaults
setuptools                45.2.0                   py36_0    defaults
sharedmem                 0.3.5                    py36_0    aramislab
simplejson                3.17.0           py36h516909a_0    conda-forge
sip                       4.19.8           py36hf484d3e_0    defaults
six                       1.14.0                   py36_0    defaults
sparqlwrapper             1.8.2                 py36_1000    conda-forge
sqlite                    3.31.1               h7b6447c_0    defaults
suitesparse               4.5.6           blas_openblash17e8c26_1201  [blas_openblas]  <unknown>
sympy                     1.5.1                    py36_1    conda-forge
tbb                       2020.1               hc9558a2_0    conda-forge
tensorboardx              2.0                      pypi_0    pypi
terminado                 0.8.3                    py36_0    defaults
testpath                  0.4.4                      py_0    defaults
tk                        8.6.8                hbc83047_0    defaults
toolz                     0.10.0                     py_0    conda-forge
torchvision               0.5.0                py36_cu101    file:///home/geng/%E4%B8%8B%E8%BD%BD
tornado                   6.0.3            py36h7b6447c_3    defaults
traitlets                 4.3.3                    py36_0    defaults
traits                    6.0.0            py36h516909a_0    conda-forge
urllib3                   1.25.7                   py36_0    conda-forge
wcwidth                   0.1.8                      py_0    defaults
webencodings              0.5.1                    py36_1    defaults
wheel                     0.34.2                   py36_0    defaults
widgetsnbextension        3.5.1                    py36_0    defaults
xgboost                   0.80            py36hf484d3e_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xvfbwrapper               0.2.9                 py36_1001    conda-forge
xz                        5.2.4                h14c3975_4    defaults
zeromq                    4.3.1                he6710b0_3    defaults
zipp                      2.2.0                      py_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7             h0a35d5f_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge

**Comment by 921974496** [comment]
![image](https://user-images.githubusercontent.com/49221720/76136807-8a3bcd00-6070-11ea-83b6-e93d6ebbaa93.png)
What is the structure of these two directories？

**Comment by mdiazmel** [comment]
> File "/home/AD-DL/clinicadl/clinicadl/preprocessing/T1_linear.py", line 25, in preprocessing_t1w
> from clinica.utils.inputs import check_bids_folder
> ImportError: No module named clinica.utils.inputs

Could you please show me the output of these commands 
```
conda activate clinicadl_env
conda list | grep "clinica"
```
?

**Comment by 921974496** [comment]
> > File "/home/AD-DL/clinicadl/clinicadl/preprocessing/T1_linear.py", line 25, in preprocessing_t1w
> > from clinica.utils.inputs import check_bids_folder
> > ImportError: No module named clinica.utils.inputs
> 
> Could you please show me the output of these commands
> 
> ```
> conda activate clinicadl_env
> conda list | grep "clinica"
> ```
> 
> ?

![image](https://user-images.githubusercontent.com/49221720/76140143-52de1800-6092-11ea-8f92-2633f8bb6aba.png)

**Comment by mdiazmel** [comment]
> What is the structure of these two directories？

`BIDS_DIR` is the input dir. BIDS (Brain Imaging Data Structure) is the standard adopted for the organisation of the datasets. You can look for a detailed description in the [official link](https://bids.neuroimaging.io/) or [here](http://www.clinica.run/doc/BIDS/).

`CAPS_DIR` for the preprocessing is the output dir. The caps structure is detailed [here](http://www.clinica.run/doc/CAPS/Introduction/).

**Comment by mdiazmel** [comment]
> > > File "/home/AD-DL/clinicadl/clinicadl/preprocessing/T1_linear.py", line 25, in preprocessing_t1w
> > > from clinica.utils.inputs import check_bids_folder
> > > ImportError: No module named clinica.utils.inputs
> > 
> > 
> > Could you please show me the output of these commands
> > ```
> > conda activate clinicadl_env
> > conda list | grep "clinica"
> > ```
> > 
> > 
> > ?
> 
> ![image](https://user-images.githubusercontent.com/49221720/76140143-52de1800-6092-11ea-8f92-2633f8bb6aba.png)

It seems that you haven't installed `clinicadl` (inside the `clinicadl_env` environment). What's the exact command that generates the error ?

**Comment by 921974496** [comment]
> > > > File "/home/AD-DL/clinicadl/clinicadl/preprocessing/T1_linear.py", line 25, in preprocessing_t1w
> > > > from clinica.utils.inputs import check_bids_folder
> > > > ImportError: No module named clinica.utils.inputs
> > > 
> > > 
> > > Could you please show me the output of these commands
> > > ```
> > > conda activate clinicadl_env
> > > conda list | grep "clinica"
> > > ```
> > > 
> > > 
> > > ?
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/49221720/76140143-52de1800-6092-11ea-8f92-2633f8bb6aba.png)
> 
> It seems that you haven't installed `clinicadl` (inside the `clinicadl_env` environment). What's the exact command that generates the error ?

![image](https://user-images.githubusercontent.com/49221720/76140290-c46a9600-6093-11ea-806c-33c6efaff746.png)

**Comment by mdiazmel** [comment]
I think that there is a problem with your $PYTHONPATH, the path where Python search for installed libraries. 

I replicated the installation steps in a fresh new installation (an Ubuntu machine) and normally the output of the command `conda list | grep "clinica"` should show these lines:
```
# packages in environment at /Users/mdiaz/conda/envs/clinicadl_env:
clinica                   0.3.2                    py36_0    aramislab
clinicadl                 0.0.1                     dev_0    <develop>
```
Proposed you to delete your conda environment and create a new one, following the installation instructions in strict order.

**Comment by 921974496** [comment]
> I think that there is a problem with your $PYTHONPATH, the path where Python search for installed libraries.
> 
> I replicated the installation steps in a fresh new installation (an Ubuntu machine) and normally the output of the command `conda list | grep "clinica"` should show these lines:
> 
> ```
> # packages in environment at /Users/mdiaz/conda/envs/clinicadl_env:
> clinica                   0.3.2                    py36_0    aramislab
> clinicadl                 0.0.1                     dev_0    <develop>
> ```
> 
> Proposed you to delete your conda environment and create a new one, following the installation instructions in strict order.

Thank you very much. I'll try

**Comment by 921974496** [comment]
> > I think that there is a problem with your $PYTHONPATH, the path where Python search for installed libraries.
> > I replicated the installation steps in a fresh new installation (an Ubuntu machine) and normally the output of the command `conda list | grep "clinica"` should show these lines:
> > ```
> > # packages in environment at /Users/mdiaz/conda/envs/clinicadl_env:
> > clinica                   0.3.2                    py36_0    aramislab
> > clinicadl                 0.0.1                     dev_0    <develop>
> > ```
> > 
> > 
> > Proposed you to delete your conda environment and create a new one, following the installation instructions in strict order.
> 
> Thank you very much. I'll try

![image](https://user-images.githubusercontent.com/49221720/76142778-bfb1dc00-60ab-11ea-8647-e214f6a8fe05.png)

**Comment by 921974496** [comment]
Hi，The data preprocessor can run normally, but there will be errors in the process。
  File "/home/geng/anaconda3/envs/clinicadl_env/lib/python3.6/site-packages/nipype/pipeline/plugins/tools.py", line 82, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details

**Comment by 921974496** [comment]
This is an error message

Traceback (most recent call last):
  File "/home/geng/anaconda3/envs/clinicadl_env/bin/clinicadl", line 11, in <module>
    load_entry_point('clinicadl', 'console_scripts', 'clinicadl')()
  File "/home/geng/PycharmProjects/AD-DL/clinicadl/clinicadl/main.py", line 23, in main
    args.func(args)
  File "/home/geng/PycharmProjects/AD-DL/clinicadl/clinicadl/cli.py", line 11, in preprocessing_t1w_func
    wf.run(plugin='MultiProc', plugin_args={'n_procs': args.nproc})
  File "/home/geng/anaconda3/envs/clinicadl_env/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/home/geng/anaconda3/envs/clinicadl_env/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 192, in run
    report_nodes_not_run(notrun)
  File "/home/geng/anaconda3/envs/clinicadl_env/lib/python3.6/site-packages/nipype/pipeline/plugins/tools.py", line 82, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details

**Comment by mdiazmel** [comment]
Can you inspect the crash file (it is normally generated in the folder where you launch the application `clinicadl`) ? You can do this using this command: `nipypecli crash crashfile-date-time.pklz`
Notice that to execute preprocessing you need to have [ANTs](http://stnava.github.io/ANTs/) previously installed.

**Comment by alexandreroutier** [comment]
Dear user,

Are you still facing this issue? You opened another issue (issue #6) so I was wondering if we could close this issue.

Best,
Alexandre
