### ISSUE TITLE
Add ANTs as requirement to execute preprocessing

### ISSUE THREAD

**Issue by mdiazmel** [aramis-lab/clinicadl#4]
[ANTs](http://stnava.github.io/ANTs/) is used to perform image registration during the preprocessing. This requirement must be added to the README page.

**Comment by alexandreroutier** [comment]
Hi!

You can check this dependency in ClinicaDL by using check_ants() from `clinica.utils.check_software` before the execution of the pipeline. 

(regarding your upcoming pipeline in Clinica, this will be done in `info.json`)
