### ISSUE TITLE
Implement classify / test

### ISSUE THREAD

**Issue by 14thibea** [aramis-lab/clinicadl#48]
This issue is to discuss the implementation of `clinicadl classify` (and eventually `clinicadl test`) as discussed in https://github.com/aramis-lab/AD-DL/pull/45.

What have to be discussed:
1. Must the input folder have a fixed structure, or should we give the json path / model path ?
2. Shall there be two pipelines depending on the presence of the true label or not (resp `classify` and `test`) or should we use a flag (such as `--true_labels`) ?
3. Where are stored the results ? Do the user give the output directory and we could write a json file to remember which model / caps / tsv file was used or is it stored in the experiment folder ?

**Comment by alexandreroutier** [comment]
Based on the discussion with @14thibea, @mdiazmel and @nburgos:

1. We will use a fixed structure.

2. Only one pipeline. `clinicadl classify ` does not contain many flags (compared to `clinicadl train`), we will tend to create a `--no_labels` flag (TBD).

3. On default, within the `result` folder (where the training was done), otherwise, the user can specify with a flag (e.g. `--output_folder` TBD).

**Comment by mdiazmel** [comment]
From the side of `clinicadl classify` these changes will be taken into account in PR #34 .

**Comment by 14thibea** [comment]
Some features must be added:
- implement no_labels choice
- choose on which best model the evaluation is performed (default will evaluate all available models).

**Comment by 14thibea** [comment]
@mdiazmel what do you think of having two possibilities for `tsv_path` argument:
- if `tsv_path` includes the filename (ends with .tsv) the corresponding file is read.
- if `tsv_path` is a directory, then the tsv files corresponding to the specified diagnoses are read (this will be useful so it can be used directly on the output of `clinicadl tsvtool split` which outputs one tsv per diagnosis)

**Comment by mdiazmel** [comment]
I thing that this could be a nice feature, but we must be sure that the help message (and the future documentation) are clear about the double behavior of `tsv_path`. 
Implementing this feature can allow us to have a test describing the whole pipeline!
