### ISSUE TITLE
Expanding Modality Support for ML Classification in ClinicaDL

### ISSUE THREAD

**Issue by souravraha** [aramis-lab/clinicadl#515]
The current documentation on modality support for ML classification in ClinicaDL provides information on only three modalities (https://clinicadl.readthedocs.io/en/latest/Preprocessing/Extract/#modality-arguments). However, there is a need to explore and clarify the inclusion of additional modalities, such as DTI (Diffusion Tensor Imaging) images from ADNI (Alzheimer's Disease Neuroimaging Initiative).

**Request for Clarification:**
- Can DTI images from ADNI be used for ML classification in ClinicaDL?
- If yes, what are the specific steps or considerations for incorporating DTI images into the ML classification workflow?

This enhancement request aims to improve the documentation by providing comprehensive information on supported modalities, ensuring users can leverage a wider range of data sources for ML classification tasks.

**Comment by camillebrianceau** [comment]
Hello @souravraha,

Unfortunately, you can't use DTI images for Classification in ClinicaDL for now, but we'll try to create this option for the next release. 

Thanks for your interest in ClinicaDL, 
Camille
