### ISSUE TITLE
Clarification needed on `TSV_DIRECTORY` for Training after using `prepare-experiment`

### ISSUE THREAD

**Issue by souravraha** [aramis-lab/clinicadl#527]
Following the execution of the `clinicadl tsvtools prepare-experiment --n_test 0.10 -vt kfold --n_validation 10 labels/labels.tsv` command to create splits for experimentation, I am facing confusion regarding the correct specification of the `TSV_DIRECTORY` for subsequent training (`clinicadl train classification [OPTIONS] CAPS_DIRECTORY PREPROCESSING_JSON TSV_DIRECTORY OUTPUT_MAPS_DIRECTORY`). 

I am utilizing the latest development version of ClinicaDL on Ubuntu 20.04, with a dataset containing T1w images sourced from ADNI. Despite various attempts, such as specifying `labels/split`, errors persist, including messages like "No validation.tsv found." Additionally, using `labels/split/10-fold` results in errors such as "No train.tsv found." 

While opting for `labels/split/10-fold/split-1` would train each split independently, this method may not be the most efficient. Clear guidelines are required regarding the expected folder structure and the correct approach for specifying the TSV folder for training subsequent to the `prepare-experiment` step.

Could you please investigate and provide guidance on establishing an appropriate TSV folder structure to ensure seamless training post-split creation?

Thank you.

**Comment by camillebrianceau** [comment]
Hello @souravraha ! 

The correct specification for the `TSV_DIRECTORY` is `labels/split/10-fold`. However, you need to specify in your training command line that you're performing cross-validation by using the `--n_splits` option to indicate the number of splits (k) in the case of k-fold cross-validation.

Your command line should look like this:
`clinicadl train classification [OPTIONS] CAPS_DIRECTORY PREPROCESSING_JSON TSV_DIRECTORY OUTPUT_MAPS_DIRECTORY --n_splits 10`

Do not hesitate if you have any other questions,
Camille

**Comment by souravraha** [comment]
> Hello @souravraha !
> 
> The correct specification for the `TSV_DIRECTORY` is `labels/split/10-fold`. However, you need to specify in your training command line that you're performing cross-validation by using the `--n_splits` option to indicate the number of splits (k) in the case of k-fold cross-validation.
> 
> Your command line should look like this: `clinicadl train classification [OPTIONS] CAPS_DIRECTORY PREPROCESSING_JSON TSV_DIRECTORY OUTPUT_MAPS_DIRECTORY --n_splits 10`
> 
> Do not hesitate if you have any other questions, Camille

Thanks! This works.

As I run this, it displays 
`Could not determine if CAPS is a CAPS or BIDS directory. Clinica will assume this is a CAPS directory.`
over and over. Is there a way out of this?
