### ISSUE TITLE
How to train single CNN of 3D Patch?

### ISSUE THREAD

**Issue by 921974496** [aramis-lab/clinicadl#57]
When I use 3D Patch to train the network, the parameter is set to Singel, there is an error. The .pt file (the entire individual) is missing, but I have 36 3D patch files

**Comment by mdiazmel** [comment]
Hi, 

Can you tell us exactly the command line that you entered and the error message that you got it?
In the meanwhile try to verify the following items:

- You are running `clinicadl` with the most recent commit from the master branch of the repository.
- Add the option ` --use_extracted_patches` to your command line.

Thanks,

**Comment by 921974496** [comment]
> Hi,
> 
> Can you tell us exactly the command line that you entered and the error message that you got it?
> In the meanwhile try to verify the following items:
> 
> * You are running `clinicadl` with the most recent commit from the master branch of the repository.
> * Add the option ` --use_extracted_patches` to your command line.
> 
> Thanks,
This is the command I entered：
clinicadl train patch cnn /home/geng/ADNI2/caps t1-linear /home/geng/ADNI2/tsv /home/geng/ADNI2/resault "Conv4_FC3"  --batch_size 12 --evaluation_steps 20  --diagnoses sMCI pMCI  --n_splits 5 --split 3 --accumulation_steps 1 --epochs 200 --learning_rate 1e-5 --weight_decay 1e-3 --patience 20 --use_extracted_patches --selection_threshold 0.7 --dropout 0.5

After completing your suggestion, there is still an error：
FileNotFoundError: [Errno 2] No such file or directory: '/home/geng/ADNI2/caps/subjects/sub-ADNI002S4229/ses-M06/deeplearning_prepare_data/image_based/t1_linear/sub-ADNI002S4229_ses-M06_T1w_space-MNI152NLin2009cSym_desc-Crop_res-1x1x1_T1w.pt'
image_based？ I only have patch_based folder 。 image_based  should be the entire brain MRI folder。

**Comment by 14thibea** [comment]
Hi,

Actually the Dataset which prepares patches needs the full image to find automatically the number of patches based on the size of the full image + the patch size + the patch stride. This is why it is looking for the full image.
In https://github.com/aramis-lab/AD-DL/pull/58 it will look for the original nifti file if it does not find the tensor (right now it is only looking for the tensor). It should fix the problem.
