### ISSUE TITLE
single -cnn 3Dpatch moudle

### ISSUE THREAD

**Issue by 921974496** [aramis-lab/clinicadl#75]
Are the models used by 3Dpatch multiple CNN and single CNN all Conv4_FC3?

**Comment by 14thibea** [comment]
Hello,

This model corresponds to the one used in [our paper](https://arxiv.org/abs/1904.07773). We only provided the final architecture that was selected after a basic architecture search excluding our test set.
However, you can easily add your custom models by writing their classes in `clinicadl/tools/deep_learning/models/patch_level.py` and importing then in `clinicadl/tools/deep_learning/models/__init__.py`.
Then you should be able to train them by calling `clinicadl train patch (multi)cnn <caps_dir> t1-linear <tsv_path> <results_dir> <custom_class_name>.
Please tell us if you encounter any problem !
