### ISSUE TITLE
Unit testing wrong

### ISSUE THREAD

**Issue by CCF0211** [aramis-lab/clinicadl#8]
Hello, your work is amazing. I tested it after the installation and found the following errors. Can you help me solve them?

![111](https://user-images.githubusercontent.com/34269940/81809319-c5b4b500-9553-11ea-923b-3f2550a5af4e.png)

**Comment by alexandreroutier** [comment]
Hi!

Thanks for your interest! :)

I installed this repo and had the same behaviour. I let @mdiazmel confirm but I think you need to fill the missing variables in the following file:
```text
$ cat clinicadl/tests/test_preprocessing.py
# coding: utf8

from clinicadl.preprocessing.T1_lineal import preprocessing_t1w

bids_dir =
caps_dir =
tsv_file =
working_dir =
nproc = 2

wf = preprocessing_t1w(args.bids_directory,
        args.caps_dir,
        args.tsv_file,
        args.working_directory)
```
In practice, it simply runs `clinicadl preprocessing` command :)

In my opinion, you can safely type `pytest clinicadl/tests/test_cli.py` then run directly `clinicadl preprocessing...` as explained in the Wiki.

Once @mdiazmel will give further details, we will clarify the Wiki or update the code, sorry about that.

Best,
Alexandre

**Comment by alexandreroutier** [comment]
BTW, do not forget to install [ANTs](https://stnava.github.io/ANTs/) if you want to run the preprocessing pipeline.

**Comment by mdiazmel** [comment]
Hi @CC0624 ,

I confirm  the answer of @alexandreroutier . We are currently working in the unit test suite, and for the moment only the CLI part is tested using `pytest`. We are planning to provide unit tests for the other tasks in the future. If you want to run successfully the tests maybe you can use a command like this one:
```
pytest clinicadl/tests/test_cli.py
```
You can also try the command for preprocessing directly, in your terminal:
```
clinicadl preprocessing <bids_dir> <caps_dir> <working_dir> --np 32
```
Cheers,

**Comment by CCF0211** [comment]
Thanks, by the way, if I need to convert ADNI data to BIDS, can I download raw data without preprocessing from ADNI website?

**Comment by alexandreroutier** [comment]
> Thanks, by the way, if I need to convert ADNI data to BIDS, can I download raw data without preprocessing from ADNI website?

I am not sure what do you mean by mean "raw data without preprocessing". We gave some details on [`adni-2-bids` converter](http://www.clinica.run/doc/Converters/ADNI2BIDS/#modalities-supported) regarding which images to download:
> T1-weighted MRI When several scans are available for a single session, the preferred scan (as identified in MAYOADIRL_MRI_IMAGEQC_12_08_15.csv) is chosen. If a preferred scan is not specified then the higher quality scan (as defined in MRIQUALITY.csv) is selected. If no quality control is found, then we choose the first scan for the visit. Gradwarp, B1-inhomogeneity corrected and N3 bias field corrected images are selected. 1.5 T images are preferred for ADNI 1 since they are available for a larger number of patients.

I hope this answers your question.

Best,
Alex

**Comment by alexandreroutier** [comment]
@CC0624: We have clarified this issue into PR #9 

Do not hesitate to open another issue on this repo or Clinica or writing on the Clinica forum.

Best,
Alex
