### ISSUE TITLE
Preprocessing: Missing ANTs software

### ISSUE THREAD

**Issue by esheee** [aramis-lab/clinicadl#94]
Hi, 

I'm a highschooler doing research for Alzheimer's Disease diagnosis and I ran into an issue when I did the preprocessing command on my MacBook. It was saying I'm missing ANTs software, do I need it and where would I find it? I also ran pip3 command and it didn't seem to install it. I have attached a screenshot of the error below. I greatly appreciate it if someone can help me.

![image](https://user-images.githubusercontent.com/44381546/90297274-d28ec080-de42-11ea-931c-c4cf5496d815.png)

**Comment by alexandreroutier** [comment]
Hello,

Thank you for your interest in AD-DL repo :)

We added recently documentation for [ClinicaDL](https://clinicadl.readthedocs.io/) where we explained that [ANTs software](https://stnava.github.io/ANTs/) needs to be installed in order to run `t1-linear` pipeline.

You can install from source code or symply use conda to install it: `conda install -c aramislab ants`

Please tell me if this solves your issue :)

Best,
Alex

**Comment by esheee** [comment]
Thank you so much, Alex, it worked! Now I have a small question, I ran the preprocessing command but it seems like I'm missing "arguments." I also updated the conda to the latest version (4.8.4). Im pasting the error, greatly appreciate your help. :)
![image](https://user-images.githubusercontent.com/44381546/90318197-b7c05880-dee3-11ea-8c80-15f6e77a20eb.png)
Thanks, 
Esha Cyril

**Comment by alexandreroutier** [comment]
Hi!

You're welcome :-)

Based on your 1st post and assuming that `ADNI` and  `AIBL` are folders in BIDS format, the syntax to run the preprocessing would look like this: `clinicadl preprocessing ADNI ADNI_CAPS AD.tsv WD_ADNI`.

We recently updated the ClinicaDL software and added a documentation here: https://clinicadl.readthedocs.io/en/latest/

I would advice you to install the latest version of ClinicaDL explained in the [installation guide](https://clinicadl.readthedocs.io/en/latest/Installation/) then follow the instructions of the preprocessing pipeline (now called [`clinicadl preprocessing t1-linear` pipeline](https://clinicadl.readthedocs.io/en/latest/Run/T1_Linear/)), we simplified a little bit how to use the pipeline.

With this new version of `clinicadl`, the syntax would simply be:
```
clinicadl preprocessing t1-linear ADNI ADNI_CAPS
clinicadl preprocessing t1-linear AIBL AIBL_CAPS
```

Best, 
Alex

**Comment by esheee** [comment]
Hi Alex, 

I hope you are doing well. I tried what you recommended and I'm still having some trouble, do you think we could have a short 5-10 zoom call so you can help me? It seems like the path setting and variable is missing somewhere and I've updated the latest Clinical and installed ants as you recommended. My email: ecyril001@gmail.com, so I can send a zoom invite. Greatly appreciate it since I'm under a time crunch.

Thanks, 
Esha Cyril

**Comment by esheee** [comment]
Heres the screenshot of my error. Thank you so much for all your help! :)
![image](https://user-images.githubusercontent.com/44381546/90711197-ee380380-e254-11ea-9617-db44f9893fce.png)

**Comment by esheee** [comment]
![image](https://user-images.githubusercontent.com/44381546/90856078-fddb4900-e335-11ea-9c26-a9c68c967b65.png)
Here is the updated error. It would be really great if you could help me for a few minutes! :)

**Comment by 14thibea** [comment]
Hi Esha,

Based on your last update it seems that the update of ClinicaDL was not successful...
Try the following commands before relaunching the preprocessing:
```
conda activate clinicadlEnv
pip install clinicadl -U
```
