### ISSUE TITLE
Preprocessing command: missing "arguments"

### ISSUE THREAD

**Issue by esheee** [aramis-lab/clinicadl#95]
Hi,

Im a high schooler using AD-DL for research and I have a small question, I ran the preprocessing command but it seems like I'm missing "arguments." I also updated the conda to the latest version (4.8.4). How can I solve this? I'm pasting the error, greatly appreciate your help. :)
![image](https://user-images.githubusercontent.com/44381546/90321803-11378000-df02-11ea-878c-d9acffa5f029.png)

image
Thanks,
Esha Cyril

**Comment by alexandreroutier** [comment]
Hi,

I answered this question in Issue #94.

Please continue the conversation in Issue #94. :)

Best,
Alex
