### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by esheee** [aramis-lab/clinicadl#96]
![image](https://user-images.githubusercontent.com/44381546/90822575-88e22200-e2e9-11ea-956c-826356db19b3.png)
Hi, Im a high schooler, Esha Cyril and I was wondering if someone could help me fix the error above. I am using this code for research on Alzheimer's Disease diagnosis. It would be great if someone could provide some insight.
Thanks!
Esha Cyril :)

**Comment by alexandreroutier** [comment]
Hi!

You are using an "old" version of ClinicaDL so the syntax is incorrect. You can either adapt the syntax (that I explained in Issue #94) or install the latest version (explained [here](https://clinicadl.readthedocs.io/)).

To understand better how to use ClinicaDL, we wrote educational support that can be read here: https://aramislab.paris.inria.fr/clinicadl/tuto/intro.html Some pages can be opened with Google Collab so you can follow how to run `t1-linear` with a BIDS dataset (in this case, OASIS).

My advise would be you to follow the tutorial, install the new version of ClinicaDL then run `t1-linear` :)

Best,
Alexandre

**Comment by esheee** [comment]
Thank you, Alex. My apologies for taking your time. I did install a new ClinicaDL as you suggested in #94. Anyways, I re-ran it with the -u option and tested all the way -h to see everything is fine. 

The problem I am struggling with now is the right directories of the file structure. Currently, I am running commands out of miniconda3 which is the folder created out from the new install within my user directory. When I ran the command with t1-linear, I got an error saying there is no directory. I went to create one but it looks for files within the t1-linear directory.

I am more of a biology person with just a basic comp science background so a few minutes from you on a zoom call or something can fix my issues quickly as I have pressing report to write. Thank you so much, I owe you! :)

Esha

**Comment by esheee** [comment]
Hi Alex, 

I tried to make some progress and followed all the documentation you mentioned. Please kindly take a look at this error. I'll continue to make some more progress and look into this. Thank you so much! :)
![image](https://user-images.githubusercontent.com/44381546/90949752-ecf70a00-e3ff-11ea-9fa4-7d10de677cb7.png)

**Comment by 14thibea** [comment]
Hi!

Your first command line `clinica convert oasis-to-bids OasisDatabase/RawData OasisDatabase/ClinicalData OasisBids_example` looks good, except that you should remove the symbol `!` at the beginning (it is only needed when executing such commands from a notebook).

**Comment by esheee** [comment]
Hi Elina, 

Thank you so much. Will you be able to have a short 5-10 minutes zoom call with me maybe I'm making some mistakes? I have a pressing commitment on my research and your quick help can greatly help me.

Thanks, 
Esha Cyril

**Comment by 14thibea** [comment]
Hi Esha,

We cannot provide technical support by zoom, but the command `clinica convert oasis-to-bids path/to/RawData path/to/ClinicadlData path/to/output` in which all expressions beginning by `path/to` are replaced by the correct paths should work.
Please tell us if it is not the case!

**Comment by esheee** [comment]
Hi Elina - I am struggling to find the right path for rawdata and clinical data. I see AD-DL and also AD-DL master and again underneath data directories.

I understand the syntax but do i select directories underneath my miniconda install? When do i select AD-DL-Master directory and what files to select? Sorry, for dumb questions. Thank you for help

**Comment by esheee** [comment]
I ran the command and found where the csv file exists but still it says the file is not found, even though I gave the right path and directory. 

![image](https://user-images.githubusercontent.com/44381546/91201915-ebef0280-e6b5-11ea-8cb6-bd895fcea4cb.png)

**Comment by esheee** [comment]
Hi Elina, 
We made some progress and ran the command as you suggested with the right input/output and images. The clinicadl application started running and created an output tsv file but the clinicadl application crashed with the following error asking me to pass this to the development team. I think we're pretty close to running this if you or someone could take a look at this I would very much appreciate it. :)
![image](https://user-images.githubusercontent.com/44381546/91233204-8f0b4080-e6e5-11ea-98fa-dbaa70639a3e.png)
![image](https://user-images.githubusercontent.com/44381546/91233262-a8ac8800-e6e5-11ea-8850-9f895a8e6420.png)
Thanks, 
Esha Cyril

**Comment by alexandreroutier** [comment]
Hi Esha,

If you look at the documentation of [`oasis-2-bids` pipeline](http://www.clinica.run/doc/Converters/OASIS2BIDS/), you will see that arguments you gave are incorrect.

The syntax to run the command is
```Text
clinica convert oasis-to-bids <dataset_directory> <clinical_data_directory> <bids_directory>
```
where:

  - `dataset_directory` is the path to the original OASIS images' directory. In your case, you gave the path to clinica data.  The path of `dataset_directory` should contain a tree like this :
```text
.
├── OAS1_0001_MR1
│   ├── FSL_SEG
│   ├── PROCESSED
│   │   └── MPRAGE
│   │       ├── SUBJ_111
│   │       └── T88_111
│   │           └── t4_files
│   └── RAW
├── ...
```
  - `clinical_data_directory` is the path to the directory where the CSV file with the clinical data is located. In your case, it seems to be `/Users/eshacyril/Desktop/New Folder With Items/`. By the way, rename `New Folder With Items/` with folder name without spaces, it may cause some troubles.
  - `bids_directory` is the path to the output directory, where the BIDS-converted version of OASIS will be stored. You can simply type `OASIS_BIDS` :)

Best,
Alex

**Comment by alexandreroutier** [comment]
Hi @esheee,

Since we don't have feedback, we will close this issue. I hope you managed to convert OASIS database.

Best,
Alex
