### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by esheee** [aramis-lab/clinicadl#97]
Hi, I'm Esha, a high schooler and I am currently doing research work on Alzheimer's Disease. I am really a novice when it comes to neural networks and I'm trying to create a basic neural network program. The (possibly dumb) question I have is can I build neural networks with just binary inputs or do I need to use an image? 

Thanks, 
Esha

**Comment by 14thibea** [comment]
Hi,

It is possible to give nearly any input to a neural network. However this library in particular only focuses on images (and more particularly on neuroimaging organized in BIDS format, then it is going to be difficult to adapt it to a very different type of input.
